version: '3'
services:

  mariadb:
      ports: 
          - ${DB_PORT}:${DB_PORT}
      build: $ABSOLUTE_PATH/requirements/mariadb
      image: $DB_IMAGE_NAME
      container_name: $DB_CONTAINER_NAME
      env_file: 
          - .env
      networks:
          - $NETWORK_NAME
      volumes:
          - inception_mariadb_volume:/var/lib/mysql
      restart: always

  nginx:
    ports:
      - ${NGINX_PORT}:${NGINX_PORT} #port exposed to the local machine
    build:
      context: $ABSOLUTE_PATH/requirements/nginx/ #where the dockerfile is
      dockerfile: Dockerfile
    container_name: $NGINX_CONTAINER_NAME
    networks:
     - $NETWORK_NAME #which network he is a part of
    env_file: .env
    volumes:
      - $ABSOLUTE_PATH/requirements/nginx/ssl:/etc/nginx/ssl
      - inception_wordpress_volume:/var/www/html
    depends_on:
      - wordpress
    restart: always 

  wordpress:
    ports:
      - ${WP_PORT}:${WP_PORT}
    build:
      context: $ABSOLUTE_PATH/requirements/wordpress
      dockerfile: Dockerfile
      args:
          - WP_PHP_USER=$WP_PHP_USER
          - WP_PHP_GROUP=$WP_PHP_GROUP
    image: $WP_IMAGE_NAME
    container_name: wordpress
    env_file: .env
    volumes:
      - inception_wordpress_volume:/var/www/html
    networks:
      - $NETWORK_NAME
    depends_on: # wordpress needs to wait for the database to be init
      - mariadb
    healthcheck:
        test: ["CMD-SHELL", "echo 'Wordpress is healthy'"]
        interval: 30s
        timeout: 10s
        retries: 3
    restart: always

volumes:
    inception_mariadb_volume:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: $ABSOLUTE_PATH$DB_VOLUME_PATH
        name: $DB_VOLUME_NAME

    inception_wordpress_volume:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: $ABSOLUTE_PATH$WP_VOLUME_PATH
        name: $WP_VOLUME_NAME

networks:
  inception:
    name: $NETWORK_NAME
    driver: bridge #automatic docker config to make the containers communicate in bridge
